### ISSUE TITLE
ModuleNotFoundError: No module named 'vtk.vtkPVServerManagerRendering'

### ISSUE THREAD

**Issue by ziqiangxu** [Kitware/light-viz#76]
Under `paraview-5.8.0`， `LightViz 1.0`， I got this error
```
xu@debian:~/app/para-view$ LightViz --paraview ROOT --data ./ParaView-v5.8.0/Remoting/Application/Testing/Data/
ls: no such file or directory: /Applications
ls: no such file or directory: /usr/local/opt/

===============================================================================
| Execute:
| $ "/home/xu/app/para-view/ParaView-5.8.0-MPI-Linux-Python3.7-64bit/bin/pvpython"
|	-dr
|	--force-offscreen-rendering
|	"/home/xu/.nvm/versions/node/v12.16.3/lib/node_modules/light-viz/server/pvw-light-viz.py"
|	--content
|	"/home/xu/.nvm/versions/node/v12.16.3/lib/node_modules/light-viz/dist"
|	--port
|	8080
|	--data
|	"./ParaView-v5.8.0/Remoting/Application/Testing/Data/"
===============================================================================

Traceback (most recent call last):
  File "/home/xu/.nvm/versions/node/v12.16.3/lib/node_modules/light-viz/server/pvw-light-viz.py", line 95, in <module>
    import light_viz_protocols as lv_protocols
  File "/home/xu/.nvm/versions/node/v12.16.3/lib/node_modules/light-viz/server/light_viz_protocols.py", line 18, in <module>
    from vtk.vtkPVServerManagerRendering import vtkSMPVRepresentationProxy, vtkSMTransferFunctionProxy, vtkSMTransferFunctionManager
ModuleNotFoundError: No module named 'vtk.vtkPVServerManagerRendering'
```

**Comment by jourdain** [comment]
LightViz has not been updated to fix ParaView 5.8 imports. If you want to use it, you can fix them by following what was done [here](https://github.com/Kitware/paraview-lite/blob/master/server/lite_protocols.py#L12-L33).

**Comment by ziqiangxu** [comment]
> LightViz has not been updated to fix ParaView 5.8 imports. If you want to use it, you can fix them by following what was done [here](https://github.com/Kitware/paraview-lite/blob/master/server/lite_protocols.py#L12-L33).

OK, I see, thank you! :smile:
